# SPDX-License-Identifier: MIT

name: Auto Approve

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve:
    name: Auto-approve owner PRs
    if: github.event.pull_request.user.login == github.repository_owner
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Approve
        run: gh pr review "${{ github.event.pull_request.number }}" --approve --repo "${{ github.repository }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        run: gh pr merge "${{ github.event.pull_request.number }}" --auto --merge --repo "${{ github.repository }}"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
